#!/bin/bash

description=$'Docker clean images - Clean the old and unused docker images.'

usage()
{
    echo "$description"
}

while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

docker rmi $(docker images -q)